name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Unit Tests
      run: npm test
    
    - name: Install Cypress
      uses: cypress-io/github-action@v5
      with:
        install: false
        start: npm start
        wait-on: 'http://localhost:8080'
        runTests: false
    
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v5
      with:
        start: npm start
        wait-on: 'http://localhost:8080'
        spec: cypress/e2e/**/*.cy.js
        record: false
      env:
        NODE_ENV: test